name: Backup Minecraft World

on:
  push:
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Zip world folder
        run: |
          mkdir -p backups
          zip -r backups/world-$(date +'%Y-%m-%d_%H-%M-%S').zip . -x ".github/*"

      - name: Commit and push backup
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add -f backups/*.zip
          git commit -m "Auto backup $(date +'%Y-%m-%d_%H-%M-%S')" || echo "No changes to commit"
          git push

