name: Backup Minecraft World

on:
  push:
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Zip world folder
        run: |
          mkdir -p backups
          zip -r backups/world-$(date +'%Y-%m-%d_%H-%M-%S').zip . -x ".github/*"

      - name: Commit and push backup
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          # Set remote to use PAT for authentication
          git remote set-url origin https://x-access-token:${GH_PAT}@github.com/${GITHUB_REPOSITORY}.git
          git add -f backups/*.zip
          git commit -m "Auto backup $(date +'%Y-%m-%d_%H-%M-%S')" || echo "No changes to commit"
          git push origin main
